version: "3"
services:
  mysql_container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
      MYSQL_DATABASE: vue_db
    ports:
      - 3306:3306
    volumes:
      # - ${MYSQL_HOST_DIR}:/var/lib/mysql
      - ./sqls/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  # web:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/user/src/app
  #   depends_on:
  #     - mysql_container

  adminer_container:
    image: adminer:latest
    depends_on:
      - mysql_container
    restart: always
    ports:
      - 8081:8080