version: "3.1"
services:
  web:
    image: jerry092383/vue-nodejs-mysql
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/user/src/app
    depends_on:
      - mysql_container

  mysql_container:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
    ports:
      - 3306:3306
    volumes:
      - .:/var/lib/mysql

  adminer_container:
    image: adminer:latest
    depends_on:
      - mysql_container
    restart: always
    ports:
      - 8081:8080